SELECT ID, EXTRACT(YEAR FROM AGE(FINISH_DATE, START_DATE))
               * 12 + EXTRACT(MONTH FROM AGE(FINISH_DATE, START_DATE)) AS MONTH_COUNT FROM project
WHERE EXTRACT(YEAR FROM AGE(FINISH_DATE, START_DATE))
          * 12 + EXTRACT(MONTH FROM AGE(FINISH_DATE, START_DATE))
          = (SELECT MAX(EXTRACT(YEAR FROM AGE(FINISH_DATE, START_DATE))
                            * 12 + EXTRACT(MONTH FROM AGE(FINISH_DATE, START_DATE))) FROM project);